config/routes.rb
Rails.application.routes.draw do

get '/welcome' => 'lots#welcome'
get '/search' => 'lots#search'
get '/borough' => 'lots#results', as:'results'

root :to => "lots#welcome"
end

app/models/lot.rb
class Lot < ActiveRecord::Base
  def self.boroughs
    Lot.select("borough").group("borough").count.keys
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lots_controller.rb
class LotsController < ApplicationController
  def welcome
    @boroughs=Lot.boroughs
  end

  def search
    # raise params.inspect
    @x ||= 0
    @y ||= @x+8

    @borough = params[:borough]
    @lots=Lot.where(borough: @borough)[@x..@y]
    @count=Lot.where(borough:@borough).count
  end

  def results
    @x = params[:x].to_i
    @y = @x+8

    @borough = params[:borough]
    @lots=Lot.where(borough: @borough)[@x..@y]
    @count=Lot.where(borough: @borough).count
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VacantLotsFinal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
<script src="http://www.gitshoes.com/repos/49.js" type='application/javascript'></script>
</body>
</html>

app/views/lots/results.html.erb
<div class="container">
  <h4 class="monkey"><%=link_to "Search", welcome_path %></h4>
  <h3 class="monkey"><%= @borough %> | Showing: <%=@x+1%>-<%=@y+1%> | Total Lots: <%=@count%></h3>

  <p class="warning">
      <span>Loading Vacant Lots.....  Click on image for details</span>
  </p>

  <p id="vacant_lots">
    <% @lots.each do |lot| %>
      <img src="http://maps.googleapis.com/maps/api/streetview?size=350x200&amp;location=<%=lot.latitude%>,<%=lot.longitude%>&amp;sensor=false&key=<%=ENV["GOOG_API"]%>" alt="Address: <%= lot.address %> | BBL: <%= lot.bbl %> | Block: <%= lot.block %> | Lot: <%= lot.lot %> | Agency/Landowner: <%= lot.agency %> | Sqft: <%= lot.area_sqft %> | Acres: <%=lot.area_acres%> | Vacant: <%= lot.is_vacant %> | Accessible: <%= lot.accessible %>"> 
    <% end %>
  </p>

  <%= link_to 'Previous', results_path(:borough=>@borough,:x => @x-9) %>
  
  <%if @y<@count%>
    <%= link_to 'Next', results_path(:borough=>@borough,:x => @x+9) %>
  <%end%>
</div>

app/views/lots/search.html.erb
<div class="container">
  <h4 class="monkey"><%=link_to "Search", welcome_path %></h4>
  <h3 class="monkey"><%= @borough %> | Showing: <%=@x+1%>-<%=@y+1%> | Total Lots: <%=@count%></h3>
  
  <p class="warning">
      <span>Loading Vacant Lots.....  Click on image for details</span>
  </p>

  <p id="vacant_lots">
    <% @lots.each do |lot| %>
      <img src="http://maps.googleapis.com/maps/api/streetview?size=350x200&amp;location=<%=lot.latitude%>,<%=lot.longitude%>&amp;sensor=false&key=<%=ENV["GOOG_API"]%>" alt="Address: <%= lot.address %> | BBL: <%= lot.bbl %> | Block: <%= lot.block %> | Lot: <%= lot.lot %> | Agency/Landowner: <%= lot.agency %> | Sqft: <%= lot.area_sqft %> | Acres: <%=lot.area_acres%> | Vacant: <%= lot.is_vacant %> | Accessible: <%= lot.accessible %>">  
    <% end %>
  </p>

  <%if @y<@count%>
    <%= link_to 'Next', results_path(:borough=>@borough,:x => @x+9) %>
  <%end%>
</div>

app/views/lots/welcome.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Hello!</h1>
    <p>Search for vacant lots in you area</p>

    <a class="btn btn-primary btn-lg" id="submit_button">
      <%= form_tag("/search", method: "get") do %>

        <%= select_tag "borough", options_for_select(@boroughs), prompt: "Select Borough", id: "borough" %>
        <%= submit_tag("Search") %>
          
      <% end %>
    </a>
  </div>
</div>

<div class="container">
  <h1>Why?</h1>
  <p id="info">Vacant lots often sit idle and are an eye sore when in fact they could bring value to the community. The purpose of this site is to help quickly identify promising lots that can be turned into something useful such as a community garden. More information on starting and organizing a community garden can be found below:</p>
  <a href="http://596acres.org/">596 Acres</a><br>
  <a href="http://www.greenthumbnyc.org/">GreenThumb NYC</a>
</div>